name: "Nuki Bridge"
description: "Nuki Local Bridge inspired by RaspiNukiBridge"
version: "1.0.0"
slug: "raspi-nuki-bridge"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8000/tcp: 8080
